// src/components/products/productsData.js
import Image1 from '../assets/houseDemo.jpg';

export const products = [
  {
    id: 1,
    name: "Apartment in Central Thessaloniki",
    description: "Spacious 4-bedroom apartment with 2 bathrooms, located on the 3rd floor. Recently renovated, 120 sqm, ideal for families. Walking distance to the sea and main shopping streets.",
    location: "City Center",
    rooms: 4,
    bathrooms: 2,
    floor: 3,
    size: 120,
    address: "Egnatia 50, Thessaloniki, Greece",
    images: [Image1, Image1, Image1],
  },
  {
    id: 2,
    name: "Modern Apartment",
    description: "Bright and modern 3-bedroom apartment with 2 bathrooms, 95 sqm, situated on the 2nd floor. Includes a large balcony with city view, located in a prestigious neighborhood.",
    location: "Luxury Area",
    rooms: 3,
    bathrooms: 2,
    floor: 2,
    size: 95,
    address: "Egnatia 50, Thessaloniki, Greece",
    images: [Image1, Image1],
  },
  {
    id: 3,
    name: "Studio Apartment",
    description: "Compact studio apartment of 45 sqm with 1 bathroom, on the 1st floor. Perfect for students or investment, located next to the university and public transport.",
    location: "Near University",
    rooms: 1,
    bathrooms: 1,
    floor: 1,
    size: 45,
    address: "Egnatia 50, Thessaloniki, Greece",
    images: [Image1, Image1, Image1],
  },
  {
    id: 4,
    name: "Luxury Penthouse",
    description: "Exclusive 3-bedroom penthouse with 3 bathrooms, 150 sqm, located on the 7th floor. Features panoramic sea view, private parking, and a spacious terrace.",
    location: "High-end Neighborhood",
    rooms: 3,
    bathrooms: 3,
    floor: 7,
    size: 150,
    address: "Egnatia 50, Thessaloniki, Greece",
    images: [Image1, Image1],
  },
  {
    id: 5,
    name: "Investment Apartment",
    description: "Cozy 2-bedroom apartment with 1 bathroom, 70 sqm, on the 4th floor. Fully rented with 7% annual yield. Close to public transport and shopping facilities.",
    location: "Close to Public Transport",
    rooms: 2,
    bathrooms: 1,
    floor: 4,
    size: 70,
    address: "Egnatia 50, Thessaloniki, Greece",
    images: [Image1, Image1, Image1],
  },
];
