export const REVIEWS_FETCH_REQUEST = "REVIEWS_FETCH_REQUEST";
export const REVIEWS_FETCH_SUCCESS = "REVIEWS_FETCH_SUCCESS";
export const REVIEWS_FETCH_FAIL = "REVIEWS_FETCH_FAIL";

export const REVIEW_ADD_REQUEST = "REVIEW_ADD_REQUEST";
export const REVIEW_ADD_SUCCESS = "REVIEW_ADD_SUCCESS";
export const REVIEW_ADD_FAIL = "REVIEW_ADD_FAIL";

export const REVIEW_DELETE_REQUEST = "REVIEW_DELETE_REQUEST";
export const REVIEW_DELETE_SUCCESS = "REVIEW_DELETE_SUCCESS";
export const REVIEW_DELETE_FAIL = "REVIEW_DELETE_FAIL";
